### ISSUE TITLE
Weapon Skills Stuck!

### ISSUE THREAD

**Issue by CrazyRobb** [Firemaw-WoW/Firemaw#12]
**Description**:

Hey. I just found out that my weapon skills are stuck at 105/105 and i'm at level 60. I should have up to 300.
Please help! /Robz

**Comment by CrazyRobb** [comment]
I can hardly hit anything above level 40 because of my lack in Weapon Skills. Really need help! Thanks!

**Comment by dermeisterz** [comment]
Has this been fixed yet and how? Been having the same issue after using the 60 boost. Was lvl 25 and skills thus at 125. But now instead of 125/300 I'm stuck at 125/125.
Help please.

**Comment by Lavacore** [comment]
Please open a ticket ingame.
