### ISSUE TITLE
weapon skills stuck after buying a boost

### ISSUE THREAD

**Issue by Sgtdicksmash** [Firemaw-WoW/Firemaw#13]
**Description**: bought a level 60 boost for my warrior and the default weapon/defence skills are 15/15 instead of 15/30. I tried restarting the game and i also tried fighting mobs my level and nothing has changed. I did buy weapon skills in SW and those appear as 1/300 so its just the default ones that are bugging out. Please fix this

**Comment by dermeisterz** [comment]
I have the same isue. My spells are stuck at 125/125. So can't get defense up or weapon skill up to even go kill normal mobs in the outside world.
Please share if a fix is found.

**Comment by Lavacore** [comment]
Please open a ticket ingame.
