### ISSUE TITLE
Mor Grayhoof spawned in LBRS

### ISSUE THREAD

**Issue by TheMeista** [Firemaw-WoW/Firemaw#18]
**Description**:  Dungeon 2 (T 0.5) summon-able boss in LBRS is spawned.

**Current behavior**: Mor Grayhoof is spawned next to War Master Voone, pulls with the boss making the fight impossible.

**Expected behavior**: Mor Grayhoof should only be spawned as part of a T 0.5 quest.

**Steps to reproduce the problem**:

1. Go to LBRS
2. Go to War Master Voone
3. Mor Grayhoof should be standing beside him.

**Source:**

**Comment by dargonax** [comment]
Fixed for now
