### ISSUE TITLE
Boosted a character, weapon skills wont go higher than 15

### ISSUE THREAD

**Issue by Halduron** [Firemaw-WoW/Firemaw#23]
Boosted a Undead Mage with the donations to 60. Weapon skills already known such as staff and wands wont go higher than 15 max.

Stuck at 15 maximum

Should be a max of 300

1. Buy a $20 Donation Level Boost
2. Boost a 60 Undead Mage (Female) 
3. Check weapon skills

**Comment by Halduron** [comment]
[WoWScrnShot_052417_235438.zip](https://github.com/Firemaw-WoW/Firemaw/files/1027929/WoWScrnShot_052417_235438.zip)

**Comment by dargonax** [comment]
Please open a ticket and we will help you out.
Open it under "character stuck - contact a GM"
