### ISSUE TITLE
Dungeon 2 bosses

### ISSUE THREAD

**Issue by Pendragon-A** [Firemaw-WoW/Firemaw#28]
**Description**: dungeon 2 quest bosses currently spawn during encounters or are already spawned and also do not yield loot

**Current behavior**: when you go into a room where any dungeon 2 quest boss should spawn they currently trigger without the required item 

**Expected behavior**: these bosses should not spawn at all during the current patch and further more they should not spawn without the appropriate quest item

**Steps to reproduce the problem**:

1. Visit the bosses in dire maul east, stratholme lbrs scholomance and ubrs

I can personally confirm the issue with mor greyhoof in lbrs and iseline in dm east

**Source:**

**Comment by puFFansiv** [comment]
Can also confirm Kormok in Scholo.
But it is possible to pull only Ras.

**Comment by dargonax** [comment]
Removed for now
