### ISSUE TITLE
More D2 bosses

### ISSUE THREAD

**Issue by Friaza0828** [Firemaw-WoW/Firemaw#30]
last boss of stratholme live

D2 bosses spawn apon entering the room

they shouldn't be there unless summoned
![world of warcraft-05-26-2017 15-56-46-405](https://cloud.githubusercontent.com/assets/28722909/26512465/c23fee78-4234-11e7-91a4-1ef985f216d9.jpg)

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Source:**

**Comment by dargonax** [comment]
Removed, thanks
