### ISSUE TITLE
NPC Animation bug

### ISSUE THREAD

**Issue by KoltS123** [Firemaw-WoW/Firemaw#36]
**Description**: An alliance NPC located on Stormwind has a looped "bow" emote.

**Current behavior**: "Bow" emote animation plays over and over on an infinite loop.

**Expected behavior**: NPC should stay on "iddle" animation unless it's interacted with.

**Steps to reproduce the problem**: Find the NPC located on the Old Town, Stormwind, on the rogue clan called SI:7. On the basement of their headquarters there's an NPC called: "Doc Mixilpixil" doing the "bow" emote over and over.**

**Source:** 
![image](https://cloud.githubusercontent.com/assets/29007298/26525003/b4b8a1ba-431e-11e7-93aa-6a546b4f0ed9.png)

![image](https://cloud.githubusercontent.com/assets/29007298/26525006/ed3aa470-431e-11e7-868c-ff73eec705d0.png)

*(Notice server time on top-right corner, showing two minutes passed and the NPC is still bowing)

**The npc should be located right bellow the staircase, but it moved because a player did a quest with it and had to roam in the room, but still can be found on the basement anyway.

**Comment by Lavacore** [comment]
Fixed, thanks
