### ISSUE TITLE
Greater Firestone not working

### ISSUE THREAD

**Issue by Memmek** [Firemaw-WoW/Firemaw#37]
**Description**:The Greater Firestone for warlocks does not seem to work as intended.

**Current behavior**: Greater Firestone (which doesnt have any description when hovering over the item.)  does not give the expected Firestone 3 buff.

**Expected behavior**: Equipping the Greater Firestone should give the Firestone 3 buff.

**Steps to reproduce the problem**:

1. Equip 1h weapon.
2. Equip Greater Firestone.
3. 

**Source:**

**Comment by Lavacore** [comment]
Fixed, thanks for reporting
