### ISSUE TITLE
Mage Quest - Gamebreaking bug for mages

### ISSUE THREAD

**Issue by Marvin11354** [Firemaw-WoW/Firemaw#4]
**Description**:
I went to azshara to the Archmage Xylem, there I could accept a questchain and instantly give up the quests but without questreward, didnt know about that. After researching this is a nice quest for mages that gives an nice item. But now i cant do this quest anymore and havent even got the nice item i need.
The Questchain is: Magic Dust, The Sirens Coral and then Destroy Morphaz, in the end part ( Destroy Morphaz) u normally need to go into sunken temple. Dont know what to do now.

Screenshots: 
http://imgur.com/a/z0OR2 - Quest done

http://imgur.com/a/puDPo Questreward

**Comment by Marvin11354** [comment]
If its fixed I would like to do the quest again for this item.

**Comment by dargonax** [comment]
I already resolved your issue.

Items that are given as rewards are part of the newer patch.
