### ISSUE TITLE
dropping more green items then blue in dungeons

### ISSUE THREAD

**Issue by jonnyb8** [Firemaw-WoW/Firemaw#47]
**Description**: since u guys hve boosted the green rate by 3x it dropps more green items then blue in stratholm and schoolomance. And its so much lost time when u do a doungen that take 2-3 hours and the only gear that dropps are green items with 20 fire resistance on it.

**Current behavior**: Tell us what happens It drops more green item then blue on smal bosses

**Expected behavior**: Tell us what should happen instead it should drop blue items

**Steps to reproduce the problem**:

1.  maybe set down the green rate to same as blue
2. or boost blue
3. or just fix it

**Source:**

**Comment by Lavacore** [comment]
Thanks for your suggestion
