### ISSUE TITLE
The Arcanist's Cookbook

### ISSUE THREAD

**Issue by tmerbs** [Firemaw-WoW/Firemaw#49]
**Description**: The Arcanist's Cookbook bugged

**Current behavior**: The Arcanist's Cookbook quest is in game already, but reward for the quest is incorrect. It doesn't give you Royal Seal of Eldre'Thalas upon completion.

**Expected behavior**: The book shouldn't be in game until we hit patch 1.11, or the reward for the book should include Royal Seal of Eldre'Thalas.

**Steps to reproduce the problem**:

1. Acquire The Arcanist's Cookbook
2. Complete the quest The Arcanist's Cookbook

**Source:** Tuna

**Comment by dargonax** [comment]
The book is not in the game, but the quest is. It is easier if you could simply open a ticket, and i'll remove the quest from your character, so you can re-complete it in newer patch.
